// This is autogenerated file , edit if only you are sure

export * from "./check-i18n-translations.interface";
export * from "./cli.interface";
export * from "./i18n-language-resolver.interface";
export * from "./i18n-options.interface";
export * from "./i18n-plural.interface";
export * from "./i18n-translation.interface";
export * from "./i18n-translator.interface";
export * from "./i18n-validation-error.interface";
export * from "./i18n-validation-exception-filter.interface";
export * from "./translate-options.interface";
export * from "./types-generator.interface";
export * from "./types.interface";
