name: test-docs

on:
  pull_request:
    branches: [main]

jobs:
  test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: Build Docusaurus website
        run: pnpm run doc:build
